-- REQUESTS
create table requests (
                          db_id bigint generated by default as identity,
                          request_id varchar(255) not null unique,
                          creationDate timestamp(6) with time zone,
                          status varchar(50),
                          primary key (db_id)
);

-- PUBLISHERS
create table request_publishers (
                                    db_id bigint generated by default as identity,
                                    request_db_id bigint,
                                    name varchar(255),
                                    version varchar(255),
                                    primary key (db_id)
);

create table publisher_options (
                                   publisher_db_id bigint not null,
                                   opt_key varchar(255) not null,
                                   opt_value varchar(255),
                                   primary key (publisher_db_id, opt_key)
);

-- GENERATIONS
create table generations (
                             db_id bigint generated by default as identity,
                             generation_id varchar(255) not null unique,
                             request_db_id bigint,
                             generatorName varchar(255),
                             generatorVersion varchar(255),
                             status varchar(50),
                             result integer,
                             reason varchar(255),
                             targetIdentifier varchar(255),
                             targetType varchar(255),
                             created timestamp(6) with time zone,
                             updated timestamp(6) with time zone,
                             finished timestamp(6) with time zone,
                             primary key (db_id)
);

create table generation_options (
                                    generation_db_id bigint not null,
                                    opt_key varchar(255) not null,
                                    opt_value varchar(255),
                                    primary key (generation_db_id, opt_key)
);

create table generation_sbom_urls (
                                      generation_db_id bigint not null,
                                      url varchar(255)
);

-- ENHANCEMENTS
create table enhancements (
                              db_id bigint generated by default as identity,
                              enhancement_id varchar(255) not null unique,
                              generation_db_id bigint,
                              request_db_id bigint,
                              enhancerName varchar(255),
                              enhancerVersion varchar(255),
                              status varchar(50),
                              result integer,
                              reason varchar(255),
                              index_value integer,
                              created timestamp(6) with time zone,
                              updated timestamp(6) with time zone,
                              finished timestamp(6) with time zone,
                              primary key (db_id)
);

create table enhancement_options (
                                     enhancement_db_id bigint not null,
                                     opt_key varchar(255) not null,
                                     opt_value varchar(255),
                                     primary key (enhancement_db_id, opt_key)
);

create table enhancement_sbom_urls (
                                       enhancement_db_id bigint not null,
                                       url varchar(255)
);

-- FOREIGN KEYS
alter table if exists request_publishers
    add constraint FK_pub_req
    foreign key (request_db_id) references requests;

alter table if exists publisher_options
    add constraint FK_pub_opt_pub
    foreign key (publisher_db_id) references request_publishers;

alter table if exists generations
    add constraint FK_gen_req
    foreign key (request_db_id) references requests;

alter table if exists generation_options
    add constraint FK_gen_opt_gen
    foreign key (generation_db_id) references generations;

alter table if exists generation_sbom_urls
    add constraint FK_gen_urls_gen
    foreign key (generation_db_id) references generations;

alter table if exists enhancements
    add constraint FK_enh_gen
    foreign key (generation_db_id) references generations;

alter table if exists enhancements
    add constraint FK_enh_req
    foreign key (request_db_id) references requests;

alter table if exists enhancement_options
    add constraint FK_enh_opt_enh
    foreign key (enhancement_db_id) references enhancements;

alter table if exists enhancement_sbom_urls
    add constraint FK_enh_urls_enh
    foreign key (enhancement_db_id) references enhancements;

-- INDEXES
create index idx_requests_tsid on requests(request_id);
create index idx_generations_tsid on generations(generation_id);
create index idx_enhancements_tsid on enhancements(enhancement_id);
create index idx_gen_req_id on generations(request_db_id);
create index idx_enh_gen_id on enhancements(generation_db_id);
